/**
 * Build-time script: reads all .md from prompts/ folder, parses them, writes specs.gen.ts.
 * Run: npm run generate:agents
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { parseAgentMd, type AgentSpec } from './parse.js';

const AGENTS_DIR = import.meta.dirname;
const PROMPTS_DIR = join(AGENTS_DIR, 'prompts');

function getSlugs(): string[] {
  const files = readdirSync(PROMPTS_DIR, { withFileTypes: false }) as string[];
  const slugs = files
    .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
    .map((f) => f.replace(/\.md$/, ''))
    .filter((s) => s !== 'docs');
  slugs.sort((a, b) => {
    if (a === 'cocrates') return -1;
    if (b === 'cocrates') return 1;
    return a.localeCompare(b);
  });
  return slugs;
}

const slugs = getSlugs();
const specs: Record<string, AgentSpec> = {};
for (const slug of slugs) {
  const filePath = join(PROMPTS_DIR, `${slug}.md`);
  const content = readFileSync(filePath, 'utf-8');
  specs[slug] = parseAgentMd(content, slug);
}

const json = JSON.stringify(specs);
const escaped = json.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

const out = `/**
 * Generated by generate-specs.ts — do not edit by hand.
 * Run: npm run generate:agents
 */

import type { AgentSpec } from './parse.js';

export const AGENT_SPECS_JSON = \`${escaped}\`;

export function getAgentSpecs(): Record<string, AgentSpec> {
  return JSON.parse(AGENT_SPECS_JSON) as Record<string, AgentSpec>;
}

const _specs = getAgentSpecs();

export function getAgentSlugsFromSpecs(): string[] {
  return Object.keys(_specs).sort((a, b) => {
    if (a === 'cocrates') return -1;
    if (b === 'cocrates') return 1;
    return a.localeCompare(b);
  });
}
`;

writeFileSync(join(AGENTS_DIR, 'specs.gen.ts'), out, 'utf-8');
console.log('Wrote specs.gen.ts with', Object.keys(specs).length, 'agents');
